export const US_STATES = [
  { value: '', label: 'Seleccione un estado' },
  { value: 'AL', label: 'Alabama' },
  { value: 'AK', label: 'Alaska' },
  { value: 'AZ', label: 'Arizona' },
  { value: 'AR', label: 'Arkansas' },
  { value: 'CA', label: 'California' },
  { value: 'CO', label: 'Colorado' },
  { value: 'CT', label: 'Connecticut' },
  { value: 'DE', label: 'Delaware' },
  { value: 'FL', label: 'Florida' },
  { value: 'GA', label: 'Georgia' },
  { value: 'HI', label: 'Hawái' },
  { value: 'ID', label: 'Idaho' },
  { value: 'IL', label: 'Illinois' },
  { value: 'IN', label: 'Indiana' },
  { value: 'IA', label: 'Iowa' },
  { value: 'KS', label: 'Kansas' },
  { value: 'KY', label: 'Kentucky' },
  { value: 'LA', label: 'Luisiana' },
  { value: 'ME', label: 'Maine' },
  { value: 'MD', label: 'Maryland' },
  { value: 'MA', label: 'Massachusetts' },
  { value: 'MI', label: 'Míchigan' },
  { value: 'MN', label: 'Minnesota' },
  { value: 'MS', label: 'Misisipi' },
  { value: 'MO', label: 'Misuri' },
  { value: 'MT', label: 'Montana' },
  { value: 'NE', label: 'Nebraska' },
  { value: 'NV', label: 'Nevada' },
  { value: 'NH', label: 'Nuevo Hampshire' },
  { value: 'NJ', label: 'Nueva Jersey' },
  { value: 'NM', label: 'Nuevo México' },
  { value: 'NY', label: 'Nueva York' },
  { value: 'NC', label: 'Carolina del Norte' },
  { value: 'ND', label: 'Dakota del Norte' },
  { value: 'OH', label: 'Ohio' },
  { value: 'OK', label: 'Oklahoma' },
  { value: 'OR', label: 'Oregón' },
  { value: 'PA', label: 'Pensilvania' },
  { value: 'RI', label: 'Rhode Island' },
  { value: 'SC', label: 'Carolina del Sur' },
  { value: 'SD', label: 'Dakota del Sur' },
  { value: 'TN', label: 'Tennessee' },
  { value: 'TX', label: 'Texas' },
  { value: 'UT', label: 'Utah' },
  { value: 'VT', label: 'Vermont' },
  { value: 'VA', label: 'Virginia' },
  { value: 'WA', label: 'Washington' },
  { value: 'WV', label: 'Virginia Occidental' },
  { value: 'WI', label: 'Wisconsin' },
  { value: 'WY', label: 'Wyoming' },
  { value: 'DC', label: 'Distrito de Columbia' },
  { value: 'PR', label: 'Puerto Rico' },
];
