name: Frontend — Build & Deploy

on:
  push:
    branches: [ "staging" ]
    paths: [ "frontend/**" ]
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      target:
        description: "Deploy target"
        required: true
        default: "staging"
        type: choice
        options: [ "staging", "prod" ]

concurrency:
  group: frontend-deploy
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install & Build
        run: |
          npm ci
          npm run build -- --clearScreen=false

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Choose target dir (staging vs prod)
        id: pick
        run: |
          if [ "${{ github.event_name }}" = "release" ] || { [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ inputs.target }}" = "prod" ]; }; then
            echo "dir=/var/www/crm_frontend/v2" >> "$GITHUB_OUTPUT"
          else
            echo "dir=/var/www/crm_frontend/v2-staging" >> "$GITHUB_OUTPUT"
          fi

      - name: Rsync dist → server
        run: |
          rsync -av --delete dist/ "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ steps.pick.outputs.dir }}/"

      - name: Reload Nginx
        run: ssh "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "sudo systemctl reload nginx"
