jobs:
  smoke:
    runs-on: ubuntu-latest

    # 👇👇 AÑADE ESTO (mapea tus secrets a env con prefijo CYPRESS_)
    env:
      CYPRESS_BASE_URL:  ${{ secrets.CYPRESS_BASE_URL }}   # https://crm.totalrepairnow.com
      CYPRESS_BASE_PATH: ${{ secrets.CYPRESS_BASE_PATH }}  # api
      CYPRESS_ADMIN_USER: ${{ secrets.CYPRESS_ADMIN_USER }}  # admin@totalrepairnow.com
      CYPRESS_ADMIN_PASS: ${{ secrets.CYPRESS_ADMIN_PASS }}  # Alfa12345.

    steps:
      - uses: actions/checkout@v4

      # (opcional) paso de debug para ver que llegaron
      - name: Debug CYPRESS env
        run: |
          echo "CYPRESS_BASE_URL=$CYPRESS_BASE_URL"
          echo "CYPRESS_BASE_PATH=$CYPRESS_BASE_PATH"
          test -n "$CYPRESS_BASE_URL"
          test -n "$CYPRESS_BASE_PATH"

      # tu instalación/ejecución actual de Cypress…
      - name: Install
        run: npm ci
        working-directory: crm_tests/cypress   # <-- ajusta si aplica

      - name: Run smoke
        run: npx cypress run --spec "cypress/e2e/smoke.api.cy.js"
        working-directory: crm_tests/cypress   # <-- ajusta si aplica
