name: Smoke API (Cypress)

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Verify Cypress (npx)
        run: npx --yes cypress@13.17.0 verify

      - name: Run smoke against prod (npx)
        env:
          CYPRESS_BASE_URL: ${{ vars.CYPRESS_BASE_URL }}
          CYPRESS_ADMIN_USER: ${{ secrets.CYPRESS_ADMIN_USER }}
          CYPRESS_ADMIN_PASS: ${{ secrets.CYPRESS_ADMIN_PASS }}
        working-directory: tests/smoke
        run: npx --yes cypress@13.17.0 run --headless

      - name: Store screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: tests/smoke/cypress/screenshots
          if-no-files-found: ignore
