name: Smoke API (Cypress)

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # cada 6h (ajustable)

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Cypress deps
        working-directory: tests/smoke
        run: npm ci || npm i

      - name: Run smoke against prod
        working-directory: tests/smoke
        env:
          CYPRESS_BASE_URL: ${{ secrets.BASE_URL }}
          CYPRESS_ADMIN_USER: ${{ secrets.ADMIN_USER }}
          CYPRESS_ADMIN_PASS: ${{ secrets.ADMIN_PASS }}
        run: npx cypress run --headless

      - name: Store screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            tests/smoke/cypress/screenshots
            tests/smoke/cypress/videos
          if-no-files-found: ignore
