name: Smoke API (Cypress)

on:
  # Lánzalo a mano desde la pestaña Actions
  workflow_dispatch:
  # También cuando haya push a main y cambios en pruebas o en este workflow
  push:
    branches: [ main ]
    paths:
      - "crm_tests/cypress/**"
      - ".github/workflows/smoke.yml"

concurrency:
  group: smoke-${{ github.ref }}
  cancel-in-progress: true

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      CYPRESS_BASE_URL:  ${{ secrets.CYPRESS_BASE_URL }}
      CYPRESS_BASE_PATH: ${{ secrets.CYPRESS_BASE_PATH }}
      CYPRESS_ADMIN_USER: ${{ secrets.CYPRESS_ADMIN_USER }}
      CYPRESS_ADMIN_PASS: ${{ secrets.CYPRESS_ADMIN_PASS }}
    defaults:
      run:
        working-directory: crm_tests/cypress
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: crm_tests/cypress/package-lock.json

      - name: Debug env
        run: |
          echo "CYPRESS_BASE_URL=${CYPRESS_BASE_URL}"
          echo "CYPRESS_BASE_PATH=${CYPRESS_BASE_PATH}"

      - name: Install deps
        run: npm ci

      - name: Run smoke
        run: npx cypress run --browser electron --spec "cypress/e2e/smoke.api.cy.js"
