name: Smoke API (Cypress)

on:
  pull_request:
    branches: [ main ]
    paths:
      - "crm_tests/**"
      - "backend/**"
      - ".github/workflows/smoke.yml"
  push:
    branches: [ main ]
    paths:
      - "crm_tests/**"
      - "backend/**"
      - ".github/workflows/smoke.yml"
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: crm_tests/cypress

    # Pasamos secretos como variables CYPRESS_ (Cypress los ve como env)
    env:
      CYPRESS_BASE_URL:  ${{ secrets.CYPRESS_BASE_URL }}
      CYPRESS_BASE_PATH: ${{ secrets.CYPRESS_BASE_PATH }}
      CYPRESS_ADMIN_USER: ${{ secrets.CYPRESS_ADMIN_USER }}
      CYPRESS_ADMIN_PASS: ${{ secrets.CYPRESS_ADMIN_PASS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          # OJO: sin cache-dependency-path para evitar el error de caché

      - name: Debug repo layout (carpeta de tests)
        run: |
          echo "PWD=$(pwd)"
          ls -la
          test -f package.json && echo "OK package.json" || echo "FALTA package.json"
          test -f package-lock.json && echo "OK package-lock.json" || echo "SIN package-lock.json"

      - name: Instalar dependencias
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Imprimir variables de entorno de Cypress (sanity)
        run: |
          echo "CYPRESS_BASE_URL=${CYPRESS_BASE_URL}"
          echo "CYPRESS_BASE_PATH=${CYPRESS_BASE_PATH:-<vacío>}"
          echo "CYPRESS_ADMIN_USER=${CYPRESS_ADMIN_USER}"
          echo "CYPRESS_ADMIN_PASS=***"

      - name: Ejecutar smoke tests (headless)
        run: npx cypress run --browser chrome
